/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unified AI gateway (OpenAI compatible) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatCompletionRequest"];
                };
            };
            responses: {
                /** @description Chat completion response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatCompletionResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenants (super-admin/service token) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Tenant"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create tenant */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TenantCreateRequest"];
                };
            };
            responses: {
                /** @description Tenant created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tenant"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenant_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tenant"];
                    };
                };
            };
        };
        /** Update tenant */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenant_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TenantUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated tenant */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tenant"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (tenant scoped) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Invite user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserInviteRequest"];
                };
            };
            responses: {
                /** @description User invited */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user role/status */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List devices */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Devices */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"][];
                    };
                };
            };
        };
        put?: never;
        /** Register device */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceRegisterRequest"];
                };
            };
            responses: {
                /** @description Device registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint short-lived device token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    device_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                            /** Format: date-time */
                            expires_at?: string;
                        };
                    };
                };
            };
        };
        /** Revoke all device tokens */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    device_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vault/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vault files */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Files */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VaultFile"][];
                    };
                };
            };
        };
        put?: never;
        /** Request signed upload URL */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VaultUploadInitRequest"];
                };
            };
            responses: {
                /** @description Signed URL returned */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignedUrlResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vault/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get file metadata */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    file_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VaultFile"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete file (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    file_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vault/files/{file_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get signed download URL */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    file_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignedUrlResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vault/files/{file_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger AI analysis */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    file_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Analysis started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vault/files/{file_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AI analysis results */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    file_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Analysis payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VaultFile"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vault/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List folders */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Folders */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VaultFolder"][];
                    };
                };
            };
        };
        put?: never;
        /** Create folder */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** Format: uuid */
                        parent_id?: string;
                    };
                };
            };
            responses: {
                /** @description Folder created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VaultFolder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vault/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete folder */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    folder_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update folder (rename/move) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    folder_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        /** Format: uuid */
                        parent_id?: string;
                    };
                };
            };
            responses: {
                /** @description Folder updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VaultFolder"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/vault/upload-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upload tokens */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tokens */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadToken"][];
                    };
                };
            };
        };
        put?: never;
        /** Create upload token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UploadTokenCreateRequest"];
                };
            };
            responses: {
                /** @description Token created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadToken"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vault/upload-tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update upload token (rotate/disable) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        is_active?: boolean;
                        /** Format: date-time */
                        expires_at?: string;
                        max_file_size_mb?: number;
                    };
                };
            };
            responses: {
                /** @description Token updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadToken"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/vault/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search vault */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SearchRequest"];
                };
            };
            responses: {
                /** @description Search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results?: components["schemas"]["SearchResult"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vault/quick-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an encrypted file to the Vault via token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Upload accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuickUploadResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatMessage: {
            /** @enum {string} */
            role: "system" | "user" | "assistant";
            content: string;
        };
        ChatCompletionRequest: {
            model: string;
            messages: components["schemas"]["ChatMessage"][];
            temperature?: number;
            max_tokens?: number;
            top_p?: number;
            frequency_penalty?: number;
            presence_penalty?: number;
            stop?: string | string[];
            stream?: boolean;
            user?: string;
        };
        ChatCompletionChoice: {
            index: number;
            message: components["schemas"]["ChatMessage"];
            finish_reason: string;
        };
        ChatCompletionResponse: {
            id: string;
            object: string;
            created: number;
            model: string;
            choices: components["schemas"]["ChatCompletionChoice"][];
            usage?: {
                prompt_tokens?: number;
                completion_tokens?: number;
                total_tokens?: number;
            };
        };
        Tenant: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            status: "active" | "inactive" | "suspended";
            /** @enum {string|null} */
            tier?: "free" | "pro" | "enterprise" | null;
            settings?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TenantCreateRequest: {
            name: string;
            slug: string;
            tier?: string;
            settings?: {
                [key: string]: unknown;
            };
        };
        TenantUpdateRequest: {
            name?: string;
            status?: string;
            tier?: string;
            settings?: {
                [key: string]: unknown;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            full_name?: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member" | "viewer" | "super_admin";
            /** @enum {string} */
            status: "active" | "disabled" | "invited";
            /** Format: uuid */
            tenant_id?: string;
            mfa_enabled?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        UserInviteRequest: {
            /** Format: email */
            email: string;
            full_name?: string;
            role: string;
            /** Format: uuid */
            tenant_id: string;
        };
        UserUpdateRequest: {
            role?: string;
            status?: string;
        };
        Device: {
            /** Format: uuid */
            id: string;
            name: string;
            platform: string;
            /** Format: uuid */
            tenant_id?: string;
            /** Format: uuid */
            user_id?: string;
            last_ip?: string;
            last_user_agent?: string;
            /** Format: date-time */
            created_at?: string;
        };
        DeviceRegisterRequest: {
            name: string;
            platform: string;
            fingerprint?: string;
        };
        VaultFolder: {
            /** Format: uuid */
            id: string;
            name: string;
            path: string;
            /** Format: uuid */
            parent_id?: string | null;
        };
        VaultFile: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            vault_id: string;
            /** Format: uuid */
            folder_id?: string | null;
            filename: string;
            size_bytes: number;
            content_type: string;
            ai_summary?: string | null;
            ai_tags?: string[] | null;
            ai_category?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** @enum {string} */
            status?: "pending" | "active" | "archived" | "deleted";
        };
        VaultUploadInitRequest: {
            filename: string;
            content_type: string;
            size_bytes: number;
            /** Format: uuid */
            folder_id?: string;
            checksum?: string;
        };
        SignedUrlResponse: {
            /** Format: uuid */
            file_id: string;
            /** Format: uri */
            upload_url: string;
            /** Format: date-time */
            expires_at?: string;
        };
        UploadToken: {
            /** Format: uuid */
            id: string;
            token_prefix: string;
            allowed_types?: string[];
            max_file_size_mb?: number;
            /** Format: date-time */
            expires_at?: string | null;
            is_active?: boolean;
        };
        UploadTokenCreateRequest: {
            name: string;
            /** Format: uuid */
            vault_id: string;
            allowed_types?: string[];
            max_file_size_mb?: number;
            /** Format: date-time */
            expires_at?: string;
            auto_approve?: boolean;
        };
        SearchRequest: {
            query: string;
            /** Format: uuid */
            folder_id?: string;
            tags?: string[];
            content_types?: string[];
        };
        SearchResult: {
            file?: components["schemas"]["VaultFile"];
            score?: number;
            snippet?: string;
        };
        QuickUploadResponse: {
            success: boolean;
            /** Format: uuid */
            file_id: string;
            filename: string;
            size_bytes: number;
            ai_summary?: string;
            ai_category?: string;
            ai_tags?: string[];
            suggested_folder?: string;
            auto_approved?: boolean;
            duration_ms?: number;
        };
        ErrorResponse: {
            error: {
                message?: string;
                code?: string;
                type?: string;
            };
        };
    };
    responses: {
        /** @description Authentication required or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
